version: "3"
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.20
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=FundManagementService
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  person-service:
    depends_on:
      - mysqldb
    container_name: person-service
    image: person-service:latest
    restart: on-failure
    build:
      context: FundManagement/person-service
      dockerfile: Dockerfile
    ports:
      - "6868:8080"
    environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/FundManagementService",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "mypass",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
        - .m2:/root/.m2
    stdin_open: true
    tty: true
  account-service:
    depends_on:
      - mysqldb
    container_name: account-service
    image: account-service:latest
    build:
      context: FundManagement/account-service
      dockerfile: Dockerfile
    ports:
      - "6869:8081"
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/FundManagementService",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "mypass",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: