name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: build and test person-service
      run: mvn -f FundManagementService/person-service -B package --f pom.xml -D maven.test.skip=true
      
    - name: build and test account-service
      run: mvn -f FundManagementService/account-service -B package --f pom.xml -D maven.test.skip=true
